### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [ShuvalovPavel/json_validator#6]
Go ahead and implement task 2.

**Comment by ShuvalovPavel** [comment]
https://github.com/ShuvalovPavel/json_validator/commit/565e175ce30d0114e7ca838d246337c451c19369

**Comment by SemenMartynov** [comment]
```
$ docker run --rm -p 80:80 json_validator
Exception in thread "main" java.lang.IllegalStateException: InjectionManagerFactory not found.
        at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:269)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:334)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:117)
        at com.mycompany.json_validator.Main.main(Main.java:28)
```

**Comment by SemenMartynov** [comment]
OK
